sudo: required
services:
    - docker

before_install:
    - docker build -t elvisjorge/docker_multi-container -f ./client/Dockerfile.dev ./client

script:
    - docker run elvisjorge/react-test mpm test -- --coverage

after_success:
    - docker build -t elvisjorge/multi-client ./client
    - docker build -t elvisjorge/multi-nginx ./nginx
    - docker build -t elvisjorge/multi-server ./server
    - docker build -t elvisjorge/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push elvisjorge/multi-client
    - docker push elvisjorge/multi-nginx 
    - docker push elvisjorge/multi-server
    - docker push elvisjorge/multi-worker